# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.cupcake_pan.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'cupcake_pan', 'function_path': 'animated_java:cupcake_pan/variants/frosted_strawberry/apply'}
execute on passengers if entity @s[tag=aj.cupcake_pan.bone.frosting_1] run function animated_java:cupcake_pan/variants/frosted_strawberry/zzz/apply_to_bone_frosting_1
execute on passengers if entity @s[tag=aj.cupcake_pan.bone.frosting_2] run function animated_java:cupcake_pan/variants/frosted_strawberry/zzz/apply_to_bone_frosting_2
execute on passengers if entity @s[tag=aj.cupcake_pan.bone.frosting_3] run function animated_java:cupcake_pan/variants/frosted_strawberry/zzz/apply_to_bone_frosting_3
execute on passengers if entity @s[tag=aj.cupcake_pan.bone.frosting_4] run function animated_java:cupcake_pan/variants/frosted_strawberry/zzz/apply_to_bone_frosting_4
return 1