# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(top) { transformation: [-3.3333f,0f,0f,0f,0f,3.3333f,0f,1.4375f,0f,0f,-3.3333f,0f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(root) { transformation: [-2.8333f,0f,0f,0f,0f,2.8333f,0f,0f,0f,0f,-2.8333f,0f,0f,0f,0f,1f], start_interpolation: -1 }