const ffmpeg = require('fluent-ffmpeg')

function getOggTickDuration(filePath) {
	return new Promise((resolve, reject) => {
		ffmpeg.ffprobe(filePath, (err, metadata) => {
			if (err) {
				reject(err)
				return
			}
			resolve(Math.ceil(metadata.format.duration * 20))
		})
	})
}

function getVectorScoreNames(name, objective) {
	let xName = name
	let zName = name
	let xObjective = objective
	let zObjective = objective
	if (name.startsWith('@')) {
		xObjective = objective + '.x'
		zObjective = objective + '.z'
	} else {
		xName = name + '.x'
		zName = name + '.z'
	}
	return { xName, zName, xObjective, zObjective }
}

const musicLengths = new Map()

module.exports = {
	libDir: null, // default: "null", determine where mcb looks for libraries, default is the bundled install location
	generatedDirName: 'zzz', // default: "zzz", the name of the directory where mcb will put generated files
	internalScoreboardName: 'mcb.i', // default: "mcb.internal", the name of the internal scoreboard
	header: null, // default: "#This file was generated by mcb\n", the header to put at the top of supported generated files
	ioThreadCount: 1, // default: 1, the number of threads to use for IO operations, 1 is syncronous.
	getVectorScoreNames,
	musicLengths,
	setup(mcb) {
		mcb.events.onPreBuild.subscribe(async () => {
			musicLengths.set(
				'boss',
				await getOggTickDuration('../../resources/assets/cooking/sounds/music_boss.ogg')
			)
			musicLengths.set(
				'gameplay',
				await getOggTickDuration('../../resources/assets/cooking/sounds/music_gameplay.ogg')
			)
			musicLengths.set(
				'tutorial',
				await getOggTickDuration('../../resources/assets/cooking/sounds/music_tutorial.ogg')
			)
		})
	},
}
