# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.cake_pan.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'cake_pan', 'function_path': 'animated_java:cake_pan/animations/finish_baking/play'}
tag @s add aj.cake_pan.animation.finish_baking.playing
scoreboard players set @s aj.finish_baking.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:cake_pan/animations/finish_baking/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only