# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.donut_pan.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'donut_pan', 'function_path': 'animated_java:donut_pan/animations/pause_all'}
tag @s remove aj.donut_pan.animation.empty.playing
tag @s remove aj.donut_pan.animation.fill_batter.playing
tag @s remove aj.donut_pan.animation.finish_baking.playing
tag @s remove aj.donut_pan.animation.frost1.playing
tag @s remove aj.donut_pan.animation.frost2.playing
tag @s remove aj.donut_pan.animation.frost3.playing